name: build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: cd tests && mvn clean test --batch-mode -Dmaven.test.failure.ignore=true
      - name: Update existing check report
        uses: starburstdata/action-testng-report@${{ github.ref }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: build
          update_existing_check: true
          report_paths: "**/testng-results.xml"
      - name: Create new check report
        uses: starburstdata/action-testng-report@${{ github.ref }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: new check name
          report_paths: "**/testng-results.xml"
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run eslint
      - run: npm run test
